stages:
  - test
  - deploy

run_tests:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here

deploy_streamlit:
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - streamlit run your_app_name.py
  only:
    - master

 
